#!/bin/bash

echo "Setting up email alerts for wildfire detection..."

# Update system
sudo apt update && sudo apt upgrade -y

# Install Python and required packages
sudo apt install -y python3 python3-pip python3-venv

# Install system dependencies for OpenCV
sudo apt install -y libatlas-base-dev libhdf5-dev libhdf5-serial-dev libatlas-base-dev libjasper-dev libqtgui4 libqt4-test

# Create virtual environment
python3 -m venv wildfire_env
source wildfire_env/bin/activate

# Install Python packages
pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
pip install opencv-python-headless pillow requests smtplib
pip install picamera2  # For Pi camera

# Configure email settings
read -p "Enter the server email address: " email_from
read -p "Enter the server email password: " email_password
read -p "Enter the recipient email address: " email_to

cat > email_config.py << EOF
# Email Configuration for Wildfire Detection System
# Auto-generated by setup script

EMAIL_CONFIG = {
    'smtp_server': 'smtp.gmail.com',
    'smtp_port': 587,
    'email_from': '$email_from',
    'email_password': '$email_password',
    'email_to': '$email_to',
    'location': 'Remote Outpost Alpha',
    'cooldown_minutes': 5,
    'subject_prefix': '🔥 WILDFIRE ALERT - ',
    'emergency_contacts': 'Forest Service: 1-800-123-4567'
}

# Gmail App Password Instructions:
# 1. Enable 2-Factor Authentication on your Google Account
# 2. Go to Google Account settings > Security > App passwords
# 3. Generate an app password for 'Mail'
# 4. Use the 16-character password in the 'email_password' field above
EOF

echo "email_config.py created successfully"

echo "6. Setting file permissions..."
chmod 600 email_config.py
echo "Email configuration file permissions secured"
echo "✅ Setup complete!"

echo "To run the detector: python3 wildfire_detector_with_email.py"
